name: Deploy to AWS Lambda

on:
  push:
    branches:
      - feature/multi-lambda-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app
        pip install -r requirements.txt -t .

    - name: Package Lambda function
      run: |
        cd app
        zip -r lambda_function.zip . -x "*.github*"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://app/lambda_function.zip
