name: Deploy to LAYER_NAME

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/app/LAYER_NAME/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up AWS SAM
      uses: aws-actions/setup-sam@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy
      run: |
        cd lambda/app/LAYER_NAME
        sam build --use-container -t template.deploy.yaml
        sam deploy --stack-name LAYER_NAME --s3-bucket ${{ secrets.PACKAGE_S3_BUCKET }} --no-confirm-changeset
