version: '3'
services:
  localstack:
    container_name: "localstack"
    build: localstack/
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./mnt:/opt/code/localstack/mnt"
    networks:
      - container-link
    hostname: localstack.local
    ports:
      - 4566:4566
    tty: true

networks:
  container-link:
    name: localstack.internal
  