version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ../.github/workflows
        target: /workflows
